### ISSUE TITLE
30 DAYS REMAIN

### ISSUE THREAD

**Issue by qpfiffer** [qpfiffer/shithouse.tv#22] opened 2016-02-23 04:01 UTC
![](http://fuck-you-i-cant-die.shithouse.tv/Screenshot-from-2016-02-22-200110.png)

**Comment by dequis** [comment] 2016-02-23 16:57
:package:

**Comment by cblgh** [comment] 2016-10-23 21:55
💩 🏠

**Comment by dequis** [comment] 2017-08-03 02:29
Thank you for your bug report and your interest in helping the shithouse project.

I looked into this issue and reached the conclusion that this is intended behavior, so I'm closing this bug as WONTFIX.

**Closed by dequis** 2017-08-03 02:29 UTC
Labels: wontfix
